Repository Vin-Jex/dent-clack, pull requests merged in 2022-10, with the labels that each got.

#1 Create LICENSE.md
  LICENSE.md
Labels: documentation

#10 [Bug]: padding issue
  index.html
  style.css
Labels: bug

#24 Update Readme.md
  README.md
Labels: documentation, good first issue, hacktoberfest-accepted

#26 Fixed the image that was getting cropped
  index.html
  swiperjs.css
Labels: good first issue, hacktoberfest-accepted, EddieHub:good-first-issue

#27 altered readme
  README.md
Labels: bug, documentation, hacktoberfest-accepted

#34 created login page with website color scheme
  index.html
  login.css
  login.html
  style.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, EddieHub:good-first-issue

#44 NavLinks Alignment issue (Mobile) (Issue #19)
  style.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, EddieHub:good-first-issue

#51 fixes Remove Lorem Ipsum Issues #48
  index.html
Labels: hacktoberfest-accepted

#53 fixes login button issue #52
  style.css
Labels: bug, good first issue, hacktoberfest-accepted, EddieHub:good-first-issue

#54 Update style.css
  style.css
Labels: hacktoberfest-accepted

#56 Fix problems in dark mode[ changed color of dark mode and bugs] [solves #38]
  index.html
  script.js
  style.css
Labels: good first issue, hacktoberfest-accepted, EddieHub:good-first-issue

#57 mobile nav close on link clicked fixed
  script.js
Labels: good first issue, hacktoberfest-accepted, EddieHub:good-first-issue

#59 Fix login button focus styles when attempting to navigate via the keyboard
  index.html
  style.css
Labels: good first issue, hacktoberfest-accepted, EddieHub:good-first-issue

#62 Fixes [Bug]: The navbar tabs are not right aligned #60
  style.css
Labels: good first issue, hacktoberfest-accepted, EddieHub:good-first-issue

#65 Improved the title margins when going to that section through navbar
  index.html
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, EddieHub:good-first-issue

#67 modified file upload for slider testimonial slider correction
  index.html
  script.js
  style.css
Labels: good first issue, hacktoberfest-accepted, EddieHub:good-first-issue
