Repository Vin-Jex/dent-clack, pull requests merged in 2024-10, with the labels that each got.

#74 Update Documentations
  CONTRIBUTING.md
  README.md
  app/layout.tsx
  docs/PROJECT_STRUCTURE.md
  public/DentClack.png
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted, EddieHub:good-first-issue

#83 fix hero section images
  app/page.tsx
  components/LandingPage/Hero.tsx
  components/LandingPage/heroMap.tsx
  public/images/hero-images/daniel.jpg
  public/images/hero-images/lola.jpg
  public/images/hero-images/marcelo.jpg
  public/images/hero-images/nwanboje.jpg
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, EddieHub:good-first-issue

#95 Feat: Add Logo, Improve Toggle, Update The Current TopNav #77
  app/page.tsx
  components/LandingPage/heroMap.tsx
  components/atoms/themeToggle.tsx
  components/molecules/NavBar.tsx
  public/images/dentLogoDark.png
  public/images/dentLogoLite.png
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, EddieHub:good-first-issue

#94 SignIn page done
  app/layout.tsx
  app/signin/[[...signin]]/page.tsx
  middleware.ts
  package-lock.json
  package.json
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, EddieHub:good-first-issue

#97 Revert "SignIn page done"
  app/layout.tsx
  app/signin/[[...signin]]/page.tsx
  middleware.ts
  package-lock.json
  package.json
Labels: bug, hacktoberfest, hacktoberfest-accepted

#106 fix: dark/light mode #105
  components/atoms/themeToggle.tsx
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, EddieHub:good-first-issue

#112 Fix: Resolve hydration error #111
  app/(public)/layout.tsx
Labels: enhancement, good first issue, hacktoberfest, EddieHub:good-first-issue

#113 [Feature]: Authentication Page ( Sign In )
  app/(private)/auth/layout.tsx
  app/(private)/auth/signin/page.tsx
  app/globals.css
  components/Auth/SignIn.tsx
  components/atoms/Input.tsx
  components/molecules/NavBar.tsx
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, EddieHub:good-first-issue
